### ISSUE TITLE
How to run the frontend in development mode

### ISSUE THREAD

**Issue by dlfksj** [xtreme1-io/xtreme1#298]
Hi, thanks for sharing this repository.
I'm trying to run the frontend in development mode, and I have some questions.

These are what I tried
1. I used docker-compose up, but I built the four frontend images locally. (Instead downloading image from dockerhub) This is the part of docker-compose I used.
```
  # frontend:
  #   # By default, Compose will pull image from Docker Hub when no local image found.
  #   image: basicai/xtreme1-frontend:v0.9.1
  #   pull_policy: always
  #   # Uncomment this line and comment previous line to build image locally, not pull from Docker Hub.
  #   # build: ./frontend
  #   ports:
  #     - 8291:80
  frontend-main:
    build: ./frontend
    ports: 
      - 8391:8391
    volumes:
      - /home/user/xtreme1/frontend/main:/app
    command: "sleep infinity"
  frontend-image-tool:
    build: ./frontend
    ports: 
      - 8392:8392
    volumes:
      - /home/user/xtreme1/frontend/image-tool:/app
    command: "sleep infinity"
  frontend-pc-tool:
    build: ./frontend
    ports: 
      - 8393:8393
    volumes:
      - /home/user/xtreme1/frontend/pc-tool:/app
    command: "sleep infinity"
  frontend-text-tool:
    build: ./frontend
    ports: 
      - 8394:8394
    volumes:
      - /home/user/xtreme1/frontend/text-tool:/app
    command: "sleep infinity"
```
2. I also use nginx, but I removed proxy settings for frontend.
3. For frontend-main, I changed .env.development like this. Also changed the settings for the other three parts of frontend.  
```
VITE_PROXY = [["/api","http://backend:8080"]]
```
4. Run frontend modules with npm run dev.

With the settings above, the frontend and backend are connected. I can login and logout successfully and I can get list of datasets.  
But the problem is I can't get images from the database like this picture.  
![image](https://github.com/user-attachments/assets/83dede23-b9a2-4a9e-a06e-e9768827ff13)
I guess I missed some settings for minio. Can you give me some advice? thanks.
