### ISSUE TITLE
how to develop a backend for local host deployment?

### ISSUE THREAD

**Issue by A-third-of-the-sweetness** [xtreme1-io/xtreme1#326]
Currently, the front-end deployed locally can be developed
 but how can the back-end be redeveloped locally? 
Are there corresponding methods for deploying the front-end and back-end development environments? 
Because I find that the connection between the front-end, back-end, and MinIO is very deep and difficult to configure.

**Comment by A-third-of-the-sweetness** [comment]
Hello.
Currently, I'm encountering an issue where the front-end and back-end deployment on the local host are functioning properly and can communicate with each other. 

However, when uploading datasets, I get the error "Minio generate presigned url error". I have set the server in the local application-dev.yml to 8290. 

In the nginx within the Docker network, I have configured it to listen on 8190 and forward /api to 172.17.0.1:8290, allowing external communication between the front-end and back-end. 

But I'm at a loss when it comes to configuring Minio. So, I hope you can offer a good suggestion. Thank you very much.

**Comment by jotamotk** [comment]
Hi @A-third-of-the-sweetness, backend local development is documented in `backend/README.md` ("Local development"). Key points for your setup (backend on host, other services in Docker):

1. Profile: the example file is `application-local.yml`, started with `-Dspring.profiles.active=local`. If you named it `application-dev.yml`, you must start with `-Dspring.profiles.active=dev`, otherwise the default `application.yml` (with `http://minio:9000/`) is used — that host name only resolves inside the Compose network, which is why generating the pre-signed URL fails.

2. Override every Compose-internal address with host-mapped ports (ports from `docker-compose.yml`):

   ```yaml
   minio:
     endpoint: http://<host-ip>:8193/     # keep the trailing slash
   image:
     resultEvaluate:
       url: http://<host-ip>:8292/image/resultEvaluate
   pointCloud:
     resultEvaluate:
       url: http://<host-ip>:8295/pointCloud/resultEvaluate
     convertRender:
       url: http://<host-ip>:8295/pointcloud/convert_render
   dataset:
     similarity:
       url: http://<host-ip>:8294/api/v1/calcSimilarity
   ```

   (plus MySQL `localhost:8191` and Redis `localhost:8192` as in the README example)
   Prefer the host's LAN/bridge IP over `localhost` for `minio.endpoint`: the same endpoint is used to build file URLs handed to other containers (model / evaluation services), and `localhost` inside a container points to the container itself.

3. Always open the UI through nginx (`http://<host>:8190`), not the backend port. The backend rewrites the MinIO endpoint prefix into `<X-Forwarded-Proto>://<Host>/minio/`, so browser requests must go through nginx's `/minio/` location and `/api/` must keep `proxy_set_header Host $http_host` and `X-Forwarded-Proto`. Your `/api/ → 172.17.0.1:8290` forwarding is fine.
   If you change `minio.endpoint` (e.g. to `http://<host-ip>:8193/`), you must also add `proxy_set_header Host <host-ip>:8193;` to nginx's `/minio/` location (exactly the host:port of the endpoint), then run `docker compose restart nginx`. Otherwise browser uploads fail with 403 `SignatureDoesNotMatch`: the pre-signed URL is signed for the endpoint's host, while nginx forwards the request to `minio:9000`.

   ```nginx
   location /minio/ {
       ...
       proxy_set_header Host <host-ip>:8193;
       proxy_pass http://minio:9000;
   }
   ```

   The `http://localhost:8193/` example in `backend/README.md` needs the same line (`proxy_set_header Host localhost:8193;`).

4. Model URLs are stored in the database, not in `application.yml`: Models → `<model>` → Settings (e.g. `http://<host-ip>:8293/pointCloud/recognition`). For the model service contract see #329.
